phr/Pages/Account/Enable2FA.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OtpNet;
using QRCoder;
using System.Text;
using System;
using phr.Config;
using phr.Models;

namespace phr.Pages.Account
{
    public class Enable2FAModel : BasePageModel
    {
        private readonly ILogger<Enable2FAModel> _logger;

        public Enable2FAModel(ILogger<Enable2FAModel> logger)
        {
            _logger = logger;
        }

        [BindProperty]
        public string SharedKey { get; set; }
        public string QRCodeUri { get; set; }
        public string Enabled { get; set; }
        [BindProperty]
        public string VerificationCode { get; set; }
             
        public IActionResult OnGet()
        {
            var user = HttpContext.Session.GetObjectFromJson<LoginResponse>("User");
            var existingKey = HttpContext.Session.GetString("SharedKey");

            if (existingKey != null)
            {
                SharedKey = existingKey;
                QRCodeUri = GenerateQRCodeUri("IEM", user.userName, SharedKey);
                SharedKey = FormatKey(SharedKey);
            }
            else
            {
                var sharedKey = GenerateSharedKey();
                HttpContext.Session.SetString("SharedKey", sharedKey);

                QRCodeUri = GenerateQRCodeUri("IEM", user.userName, sharedKey);
                SharedKey = FormatKey(sharedKey);
            }

            _logger.LogInformation("sharedKey get: {ErrorMessage}", SharedKey);
            Enabled = HttpContext.Session.GetString("2FAEnabled");

            return Page();  
        }

        public IActionResult OnPost(string verificationCode)
        {
            // Retrieve shared key from session
            var sharedKey = HttpContext.Session.GetString("SharedKey");
            if (sharedKey == null) return RedirectToPage("/Login");

            // Validate verification code
            if (VerifyCode(sharedKey, verificationCode))
            {
                HttpContext.Session.SetString("2FAEnabled", "true");

                return RedirectToPage("/Index");
            }
                
            ModelState.AddModelError("VerificationCode", "Invalid code.");
            return Page();
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("Token");
            return RedirectToPage("/Login"); 
        }
        public IActionResult OnPostRefresh()
        {
            return RedirectToPage(); 

        }

        private string GenerateSharedKey()
        {
            var rng = new byte[10];
            using var generator = System.Security.Cryptography.RandomNumberGenerator.Create();
            generator.GetBytes(rng);
            return Base32Encoding.ToString(rng); 
        }

        private string FormatKey(string unformattedKey)
        {
            return string.Join(" ", Enumerable.Range(0, unformattedKey.Length / 4)
                .Select(i => unformattedKey.Substring(i * 4, 4)));
        }

        private string GenerateQRCodeUri(string appName, string email, string key)
        {
            using (var qrGenerator = new QRCodeGenerator())
            {
                var qrCodeData = qrGenerator.CreateQrCode($"otpauth://totp/{appName}:{email}?secret={key}&issuer={appName}&digits=6", QRCodeGenerator.ECCLevel.Q);
                var qrCode = new PngByteQRCode(qrCodeData);
                var qrCodeBytes = qrCode.GetGraphic(20);

                return Convert.ToBase64String(qrCodeBytes);
            }
        }

        private bool VerifyCode(string sharedKey, string verificationCode)
        {
            var totp = new OtpNet.Totp(Base32Encoding.ToBytes(sharedKey));
            return totp.VerifyTotp(verificationCode, out _);
        }
    }
}

phr/Pages/Account/LoginWith2FA.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OtpNet;
using phr.Config;

namespace phr.Pages.Account
{
    public class LoginWith2FAModel : PageModel
    {
        private readonly ILogger<LoginWith2FAModel> _logger;

        public LoginWith2FAModel(ILogger<LoginWith2FAModel> logger)
        {
            _logger = logger;
        }
        [BindProperty]
        public string TwoFactorCode { get; set; }

        public IActionResult OnPost()
        {
            var sharedKey = HttpContext.Session.GetString("SharedKey"); 
            _logger.LogInformation("sharedKey get: {ErrorMessage}", sharedKey);
            if (sharedKey == null) return RedirectToPage("/Login");

            if (VerifyCode(sharedKey, TwoFactorCode))
            {
                HttpContext.Session.Remove("2FARequired");
                return RedirectToPage("/Index");
            }

            ModelState.AddModelError("TwoFactorCode", "Invalid authentication code.");

            return Page();
        }

        private bool VerifyCode(string sharedKey, string verificationCode)
        {
            var totp = new OtpNet.Totp(Base32Encoding.ToBytes(sharedKey));
            return totp.VerifyTotp(verificationCode, out _);
        }
    }
}

phr/Pages/Account/Settings.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OtpNet;
using QRCoder;
using System.Text;
using System;
using phr.Config;
using phr.Models;

namespace phr.Pages.Account
{
    public class SettingsModel : BasePageModel
    {
        private readonly ILogger<SettingsModel> _logger;

        public SettingsModel(ILogger<SettingsModel> logger)
        {
            _logger = logger;
        }

        [BindProperty]
        public string SharedKey { get; set; }
        public string QRCodeUri { get; set; }
        public string Enabled { get; set; }
        [BindProperty]
        public string VerificationCode { get; set; }
             
        public IActionResult OnGet()
        {
            var user = HttpContext.Session.GetObjectFromJson<LoginResponse>("User");
            var existingKey = HttpContext.Session.GetString("SharedKey");

            if (existingKey != null)
            {
                SharedKey = existingKey;
                QRCodeUri = GenerateQRCodeUri("IEM", user.userName, SharedKey);
                SharedKey = FormatKey(SharedKey);
            }
            else
            {
                var sharedKey = GenerateSharedKey();
                HttpContext.Session.SetString("SharedKey", sharedKey);

                QRCodeUri = GenerateQRCodeUri("IEM", user.userName, sharedKey);
                SharedKey = FormatKey(sharedKey);
            }

            _logger.LogInformation("sharedKey get: {ErrorMessage}", SharedKey);
            Enabled = HttpContext.Session.GetString("2FAEnabled");

            return Page();  
        }

        public IActionResult OnPost(string verificationCode)
        {
            // Retrieve shared key from session
            var sharedKey = HttpContext.Session.GetString("SharedKey");
            if (sharedKey == null) return RedirectToPage("/Login");

            // Validate verification code
            if (VerifyCode(sharedKey, verificationCode))
            {
                HttpContext.Session.SetString("2FAEnabled", "true");
                return RedirectToPage();
            }
                
            ModelState.AddModelError("VerificationCode", "Invalid code.");
            return Page();
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Remove("Token");
            return RedirectToPage("/Login"); 
        }
        public IActionResult OnPostRefresh()
        {
            return RedirectToPage(); 
        }

        private string GenerateSharedKey()
        {
            var rng = new byte[10];
            using var generator = System.Security.Cryptography.RandomNumberGenerator.Create();
            generator.GetBytes(rng);
            return Base32Encoding.ToString(rng); 
        }

        private string FormatKey(string unformattedKey)
        {
            return string.Join(" ", Enumerable.Range(0, unformattedKey.Length / 4)
                .Select(i => unformattedKey.Substring(i * 4, 4)));
        }

        private string GenerateQRCodeUri(string appName, string email, string key)
        {
            using (var qrGenerator = new QRCodeGenerator())
            {
                var qrCodeData = qrGenerator.CreateQrCode($"otpauth://totp/{appName}:{email}?secret={key}&issuer={appName}&digits=6", QRCodeGenerator.ECCLevel.Q);
                var qrCode = new PngByteQRCode(qrCodeData);
                var qrCodeBytes = qrCode.GetGraphic(20);

                return Convert.ToBase64String(qrCodeBytes);
            }
        }

        private bool VerifyCode(string sharedKey, string verificationCode)
        {
            var totp = new OtpNet.Totp(Base32Encoding.ToBytes(sharedKey));
            return totp.VerifyTotp(verificationCode, out _);
        }
    }
}

phr/Pages/Account/LoginWith2FA.cshtml
@page
@model phr.Pages.Account.LoginWith2FAModel
@{
	Layout = "_LayoutDefault";
	ViewData["Title"] = "2FA Verification";
}

@* <h1>Two-Factor Authentication</h1> *@
@* <p>Enter the code from your authenticator app:</p> *@
@* <form method="post"> *@
@*     <label for="TwoFactorCode">Code:</label> *@
@*     <input asp-for="TwoFactorCode" name="TwoFactorCode" type="text" class="form-control" required /> *@
@*     <span asp-validation-for="TwoFactorCode" class="text-danger"></span> *@
@*     <button type="submit" class="btn btn-primary">Verify</button> *@
@* </form> *@

<div class="container d-flex justify-content-center align-items-center" style="height: 100vh;">
	<div class="card" style="max-width: 18rem;">
		<div class="card-header">
			Authenticator Code
		</div>
		<div class="card-body">
			<form method="post">
				<label for="TwoFactorCode" class="col-form-label">Enter the code from your authenticator app:</label>
				<input asp-for="TwoFactorCode" name="TwoFactorCode" type="text" class="form-control" required>
				<span asp-validation-for="TwoFactorCode" class="text-danger"></span>
				<br />
				<button type="submit" class="btn btn-primary mx-auto">Submit</button>
			</form>
		</div>
	</div>
</div>

phr/Pages/Account/Settings.cshtml
@page
@model phr.Pages.Account.SettingsModel
@{
	ViewData["Title"] = "Settings";
}

<div class="container p-2 d-flex flex-column">
	<div class="col-12 py-2 border-bottom">
		<h4><strong>Settings</strong></h4>
	</div>
	<div class="col-12 pt-4 d-grid gap-2">
		@if (Model.Enabled == null)
		{
			<div class="d-flex mb-3">
				<h3 class="align-self-center">Authentication App</h3>
				<div class="ms-auto p-2">
					<form method="post" asp-page-handler="Refresh">
						<button class="btn btn-success"><i class="bi bi-arrow-clockwise"></i></button>
					</form>
				</div>
			</div>
			<h6>Scan QR code or copy manual key to Enable Two Factor Authentication:</h6>
			<div class="d-flex justify-content-center">
				<img src="data:image/png;base64,@Model.QRCodeUri" alt="QR Code" class="img-fluid" style="height: 300px;" />
			</div>
			<div class="col-12 p-4 mt-2 rounded-4" style="background-color: #E4EDF9">
				<h6>Manual Key:</h6>
				<div class="text-primary text-center" style="font-size: 18px;">
					<strong id="textToCopy">@Model.SharedKey</strong>
					<i class="bi bi-copy cursor-pointer" id="copyButton"></i>
				</div>

			</div>
			<form method="post">
				<label class="col-form-label">Enter Authentication Code:</label>
				<input type="text" name="VerificationCode" asp-for="VerificationCode" class="form-control" required />
				<span asp-validation-for="VerificationCode" class="text-danger"></span>
				<br />
				<button type="submit" class="btn btn-primary">Verify and Enable</button>
			</form>
		}
		else
		{
			<p>2FA is already enabled.</p>
		}
		<hr>
		<button id="notifyButton" class="btn btn-primary">Enable Notifications</button>
		<form method="post" asp-page-handler="Logout">
			<button type="submit" class="btn btn-primary">Logout</button>
		</form>

	</div>
</div>

<div class="toast" id="copyToast" role="alert" style="position: absolute; top: 20px; right: 20px;" data-bs-autohide="true">
	<div class="d-flex">
		<div class="toast-body">
			Code copied to clipboard!
		</div>
		<button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
	</div>
</div>

<script>
	if (Notification.permission === 'granted') {
		document.getElementById('notifyButton').style.display = 'none';
	}

	document.getElementById('notifyButton').addEventListener('click', function() {
		Notification.requestPermission().then(function(result) {
			if (result === 'granted') {
				window.location.href = "/";
				console.log('Notification permission granted.');
			} else {
				console.log('Notification permission denied.');
			}
		});
	});

	$(document).ready(function () {
		$('#copyButton').click(function () {
			const textToCopy = $('#textToCopy').text();

			navigator.clipboard.writeText(textToCopy).then(function () {
				var toast = new bootstrap.Toast($('#copyToast')[0]);
				toast.show();
				setTimeout(function () {
					toast.hide();
				}, 2000);
			}, function (err) {
				console.error('Could not copy text: ', err);
			});
		});
	});
</script>